server:
  port: 8887

spring:
  application:
    name: customer

feign:
  hystrix:
   enabled: true
   command:
    default:
     execution:
      isolation:
       thread:
        timeoutInMilliseconds: 5000
